title: "Zin Win Thu"
description: "PhD in Aerospace Engineering | Generative AI | Aircraft Design"
url: "https://Zthu04.github.io"
baseurl: ""

author:
  name: "Zin Win Thu"
  email: "your@email.com"
  github: "Zthu04"
